1. **Types of Data**
2. **Output** and **Input** functions
3. **Lists** and Interate over List elements
4. **Tuples** and Interate over Tuple elements
5. **Dictionary** and Interate over Dictionary key and values
6. **Arrays** and **Numpy Arrays**
7. **Matrix**
8. **IF & ELSE** Statements and **FOR** Loops

1. **Types of Data**
- Boolean
- Integer
- Float
- Character/String

In [1]:
a = True
b = False

print(a & b)
print(a | b)

False
True


In [50]:
c = 150
print(c)
type(c)

150


int

In [52]:
d = 15.6
print(d)
type(d)

15.6


float

In [53]:
e = 'a'  # "a"
print(e)
type(e)

a


str

In [54]:
f = 'LINE'  # "a"
print(f)
type(f)

LINE


str

In [58]:
int(f)

ValueError: invalid literal for int() with base 10: 'LINE'

2. **Output** and **Input** functions

In [62]:
print(d)
print(e)

15.6
a


In [63]:
print('This is output function')

This is output function


In [64]:
print("This is output function")

This is output function


In [73]:
inp = input('Please enter your choice: ')
print(inp)

Please enter your choice: 4
4


In [74]:
type(inp)

str

In [75]:
int(inp) + 4

8

3. **Lists** and Interate over List elements

In [98]:
lst = [1,5,8,4,6]
print(lst)

[1, 5, 8, 4, 6]


In [127]:
lst * 3

[2, 6, 9, 5, 7, 2, 6, 9, 5, 7, 2, 6, 9, 5, 7]

In [128]:
lst + 1

TypeError: can only concatenate list (not "int") to list

In [84]:
len(lst)

5

In [90]:
lst[4] =  lst[4] + 1

In [91]:
lst

[1, 5, 8, 4, 7]

In [96]:
range(10)

range(0, 10)

In [99]:
for index in range(len(lst)):
    print(index)
    lst[index] = lst[index] + 1
print(lst)

0
1
2
3
4
[2, 6, 9, 5, 7]


In [20]:
index = 0
for num in lst:
    lst[index] = lst[index] + 1
    index = index + 1
print(lst)

[2, 6, 9, 5, 7]


In [100]:
lst2 = [1, 'd', True, 15.6]  # Mixed Data type list

In [101]:
type(lst2)

list

In [102]:
print(lst2)

[1, 'd', True, 15.6]


In [103]:
lst2[2] = False
lst2

[1, 'd', False, 15.6]

4. **Tuples** and Interate over Tuple elements

In [104]:
tup = (1,5,8,4,6)  # Tuple is and Immutable list
print(tup)

(1, 5, 8, 4, 6)


In [105]:
tup[0] = 2

TypeError: 'tuple' object does not support item assignment

In [106]:
for num in tup:
    print(num)

1
5
8
4
6


5. **Dictionary** and Interate over Dictionary key and values

In [115]:
dct = {'number': [2,5,6,6], 'char': 'a', 'string': 'word', 'boolean': True}
print(dct)

{'number': [2, 5, 6, 6], 'char': 'a', 'string': 'word', 'boolean': True}


In [116]:
for key, value in dct.items():
    print(key, " : ", value)
    if type(value) == list:
        for index in range(len(value)):
            if value[index] == 2:
                value[index] = value[index] +2
dct

number  :  [2, 5, 6, 6]
char  :  a
string  :  word
boolean  :  True


{'number': [4, 5, 6, 6], 'char': 'a', 'string': 'word', 'boolean': True}

6. **Arrays** and **Numpy Arrays**

In [117]:
import numpy as np

In [ ]:
## Not mixed. Only same types

In [121]:
arr2 = np.array([1,2,3, 15.6])
print(arr2)
print(type(arr2))
arr2.dtype

[ 1.   2.   3.  15.6]
<class 'numpy.ndarray'>


dtype('float64')

In [28]:
lst1 = [1,2,3,4,5,6,7,8,9]
print(lst1)
print(len(lst1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
9


In [31]:
arr1 = np.array(lst1)
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
arr1[8]

9

In [125]:
arr1*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [126]:
arr1+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

7. **Matrix**

In [133]:
np.array( [ [1, 2, 3],[4, 5, 6],[7, 8, 9] ] )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
np.array( [ [1, 2, 3],[4, 5, 6] ] )

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
mat1 = np.reshape(arr1, newshape = (3,3))
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
type(mat1)

numpy.ndarray

In [135]:
arr1.shape

(9,)

In [136]:
mat1.shape

(3, 3)

In [36]:
mat1.ndim

2

In [137]:
arr1.ndim

1

8. **IF & ELSE** Statements and **FOR** Loops

In [141]:
lst2 = [5,7,4,3,6,8,6,2,1]
print(lst2)
print(len(lst2))

[5, 7, 4, 3, 6, 8, 6, 2, 1]
9


In [142]:
index = 0
for element in lst2:
    print(element," : " ,index)
    index = index + 1

5  :  0
7  :  1
4  :  2
3  :  3
6  :  4
8  :  5
6  :  6
2  :  7
1  :  8


In [144]:
index = 0
for element in lst2:
    if element >= 5:
        print(element," : " ,index)
    else:
        print('element is less than 5')
    index = index + 1

5  :  0
7  :  1
element is less than 5
element is less than 5
6  :  4
8  :  5
6  :  6
element is less than 5
element is less than 5
